name: 'Immediate Restart OCI Instance'

on:
  workflow_dispatch:     # 수동 실행 가능
  push:                  # 푸시 시 자동 실행
    branches: [ "main" ] # main 브랜치 기준 (필요 시 수정)

permissions:
  contents: read

jobs:
  restart-instance:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_INSTANCE_ID: ${{ secrets.OCI_INSTANCE_ID }}

    steps:
      - name: Restart OCI Instance (SOFTRESET)
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: restart_instance
        with:
          command: 'compute instance action --instance-id $OCI_INSTANCE_ID --action SOFTRESET'

      - name: Show OCI CLI Output
        run: |
          echo "$OUTPUT" | jq .
        env:
          OUTPUT: ${{ steps.restart_instance.outputs.output }}